# Please insert new items alphabetically.

backend-hiring-reviewers:
  members: []

  channel:
    "#guild-eng-hiring"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"
    - WIP

  include_repos:
    - challenges

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"

  quotes:
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to the Product Manager.
    - Try to pair when possible.
    - Be considerate to remote workers and follow the Working from home practices https://gov-uk.atlassian.net/wiki/x/Bz_5Bw and https://gov-uk.atlassian.net/wiki/display/CT/Working+from+home+ideas
    - Who's organising the next team lunch?
    - If you're not well, don't come in to the office. And get some rest!
    - Set your Slack status to away or do not disturb so people know whether they can disturb you.
    - Has your story got points?
    - Don't forget to assign your face to a card and PR if you're working on it or reviewing.
    - Don't forget the Jabra and fisheye lens if you're dialing in people!
    - If Hangouts is being flaky, try Slack calls or appear.in!
    - I AM VENGEANCE! I AM THE NIGHT! I AM BATMAN! :batsignal:

chargeback-developers:
  members: []

  channel:
    "#squad-chargebacks-dev"
    
  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[WIP]"
    - "wip"
    - "[wip]"
    - "[AUTO-BUMP]"

  include_repos:
    - chargebacks
    - gabyves
    - image-processor
    - mercurio
    - netuno
    - vulcano
    - marte
    - judite
    - hank
    - skyler

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "doing"
    - "blocked"

ios-developers:
  members: []

  channel:
    "#ios-github"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[WIP]"
    - "wip"
    - "[wip]"
    - "[AUTO-BUMP]"
    - "[Android]"
    - "Android"

  include_repos:
    - mini-meta-repo
    - ios-cli
    - ios-credit-card
    - ios-shell

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "doing"
    - "blocked"
    - "android"

  quotes:
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to the Product Manager.

mobile-hiring-reviewers:
  members: []

  channel:
    "#guild-mobile-hiring"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[WIP]"

  include_repos:
    - mobile-challenges

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "doing"

  quotes:
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to the Product Manager.

nupay-reviewers:
  members: []

  channel:
    "#nupay-prs"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[WIP]"
    - "wip"
    - "[wip]"

  include_repos:
    - paper-street
    - angel-face
    - doorman
    - pitt
    - norton
    - ios-nupay
    - android-nupay
    - space-monkeys
    - fight-club
    - boham
    - mayhen
    - durden
    - merchants

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "doing"
    - "blocked"
    - "android"
    - WIP
    - "[WIP]"
    - "wip"
    - "[wip]"

  quotes:
    - If it's gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to the Product Manager.
    - Try to pair when possible.
    - Who's organising the next team happy hour? :beer:
